CI: use my Nix servers
- When realising derivations, prefer to use the local cache and
  cache.nixos.org, but use builds on my servers if they're available
  too.
- After a build successfully completes, if it's on the main or deploy
  branches, copy the output to my servers to save me needing to run the
  same builds again.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -59,13 +59,57 @@ jobs:
     steps:
       - name: Recover runner disk space
         uses: wimpysworld/nothing-but-nix@v10
+
       - name: Checkout
         uses: actions/checkout@v7
+
+      - name: Set up keys
+        env:
+          NIX_SIGNING_KEY: ${{ secrets.NIX_SIGNING_KEY }}
+          SSH_KEY: ${{ secrets.SSH_KEY }}
+        run: |
+          sudo mkdir -p /etc/ssh
+          printf '%s\n' "$SSH_KEY" | sudo sh -c 'umask 0077 && tee /etc/ssh/id_ed25519' >/dev/null
+
+          sudo mkdir -p /etc/nix
+          printf '%s\n' "$NIX_SIGNING_KEY" | sudo sh -c 'umask 0077 && tee /etc/nix/key' >/dev/null
+
       - name: Install Nix
         uses: DeterminateSystems/nix-installer-action@v22
         with:
           github-token: ${{ secrets.CI_REPO_ACCESS_TOKEN }}
+          extra-conf: |
+            substituters = https://cache.nixos.org?priority=100 ssh-ng://nix-ssh@jarvis.dinwoodie.org?ssh-key=/etc/ssh/id_ed25519&priority=200&base64-ssh-public-host-key=c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUJqVk1ER3pZeDFXVFh6MlMwTk9PRzd0M2pXaCt6VTRHZVJCdlhGendXSzYgcm9vdEBqYXJ2aXMK ssh-ng://nix-ssh@marvin.dinwoodie.org:52906?ssh-key=/etc/ssh/id_ed25519&priority=300&base64-ssh-public-host-key=c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSU1EclhXQ1ZXMWY5bXpRcTdsdGQrcmk2Y3krcC9jL25INlJHcVFzTDdndUYgcm9vdEBtYXJ2aW4uZGlud29vZGllLm9yZwo=
+            secret-key-files = /etc/nix/key
+
       - name: Set up Nix caching
         uses: DeterminateSystems/magic-nix-cache-action@v14
+
       - name: Run checks
-        run: nix run .#nix-run-available-checks -- --github
+        run: |
+          mkdir -p results
+          nix run .#nix-run-available-checks -- --github --add-root results/result
+          ls -l results
+
+      - name: Deploy build results
+        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/deploy'
+        run: |
+          mapfile -t build_results < <(realpath results/*)
+          wait "$!" # Check return code from realpath
+
+          # `nix copy` seems to run as the current user, not the nix daemon, so
+          # change the key owner to the current user.
+          sudo chown --changes "$USER" /etc/ssh/id_ed25519
+
+          case "$HOSTTYPE" in
+            aarch64)
+              nix copy --to 'ssh-ng://nix-ssh@jarvis.dinwoodie.org?ssh-key=/etc/ssh/id_ed25519&priority=200&base64-ssh-public-host-key=c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUJqVk1ER3pZeDFXVFh6MlMwTk9PRzd0M2pXaCt6VTRHZVJCdlhGendXSzYgcm9vdEBqYXJ2aXMK' "${build_results[@]}"
+              ;;
+            x86_64)
+              nix copy --to 'ssh-ng://nix-ssh@marvin.dinwoodie.org:52906?ssh-key=/etc/ssh/id_ed25519&priority=300&base64-ssh-public-host-key=c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSU1EclhXQ1ZXMWY5bXpRcTdsdGQrcmk2Y3krcC9jL25INlJHcVFzTDdndUYgcm9vdEBtYXJ2aW4uZGlud29vZGllLm9yZwo=' "${build_results[@]}"
+              ;;
+            *)
+              echo "::error title=Unexpected host type::Deploy step failed due to unexpected host type $HOSTTYPE"
+              exit 1
+              ;;
+          esac
